version: '3.4'
services:
  workspace-vnc:
    build:
      context: .
      dockerfile: bionic-gpu.Dockerfile
      network: host
    image: anaconda/point-cloud-analysis:bionic-gpu
    container_name: point_cloud_analytics_workspace
    volumes:
      # assignments:
      - ${PWD}/workspace/assignments:/workspace/assignments  
      # data volume:
      - ${PWD}/workspace/data:/workspace/data
      # temporary -- for imu calibration visualization
      - /home/yaoge/Workspace/stone-caring-robotics/imu_calibration/ros_melodic/src/imu_utils/data:/workspace/imu-calibration
    # network_mode: host
    ports:
      # standard vnc client:
      - 45901:5900
      # supervisord admin:
      - 49001:9001
