version: '3.4'
services:
  workspace-vnc-bionic:
    build:
      context: .
      dockerfile: bionic-gpu.Dockerfile
      network: host
    image: anaconda/point-cloud-analysis:bionic-gpu
    container_name: point_cloud_analytics_workspace
    volumes:
      # assignments:
      - ${PWD}/workspace/assignments:/workspace/assignments  
      # data volume:
      - ${PWD}/workspace/data:/workspace/data
    # network_mode: host
    ports:
      # standard vnc client:
      - 45901:5900
      # supervisord admin:
      - 49001:9001
  workspace-vnc-xenial:
    build:
      context: .
      dockerfile: xenial-gpu.Dockerfile
      network: host
    image: anaconda/point-cloud-analysis:xenial-gpu
    container_name: point_cloud_analytics_workspace
    volumes:
      # assignments:
      - ${PWD}/workspace/assignments:/workspace/assignments  
      # data volume:
      - ${PWD}/workspace/data:/workspace/data
    # network_mode: host
    ports:
      # standard vnc client:
      - 45901:5900
      # supervisord admin:
      - 49001:9001
