version: '3.4'
services:
  workspace-vnc:
    build:
      context: .
      dockerfile: xenial.Dockerfile
      network: host
    image: anaconda/point-cloud-analysis:xenial
    container_name: point_cloud_analytics_workspace
    volumes:
      # assignments:
      - ${PWD}/workspace/assignments:/workspace/assignments  
      # data volume:
      - ${PWD}/workspace/data:/workspace/data
    # network_mode: host
    ports:
      # standard vnc client:
      - 45901:5900
      # supervisord admin:
      - 49001:9001
